language: java
install: "./.travis_install.sh"
env:
  matrix:
  - TEST=fr.inria.astor.test.repair.approaches.MultiMetEngineSimpleProgramsTest
  - TEST=fr.inria.astor.test.repair.QuixBugsRepairTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.MultiPatchTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.patchsorting.PatchPriorizationTest
  - TEST=fr.inria.astor.test.repair.approaches.ExhaustiveAstorTest
  - TEST=fr.inria.astor.test.repair.approaches.jKaliTest
  - TEST=fr.inria.astor.test.repair.approaches.MutRepairTest
  - TEST=fr.inria.astor.test.repair.approaches.JGenProgTest
#  - TEST=fr.inria.astor.test.repair.approaches.IntroClassTest
  - TEST=fr.inria.astor.test.repair.approaches.EvoSuiteGenerationTest
  - TEST=fr.inria.astor.test.repair.approaches.TibraApproachTest
  - TEST=fr.inria.astor.test.repair.approaches.cardumen.CardumenApproachTest
  - TEST=fr.inria.astor.test.repair.approaches.cardumen.CardumenExahustiveTest
  - TEST=fr.inria.astor.test.repair.approaches.JGenProgEvolutionaryTest
  - TEST=fr.inria.astor.test.repair.core.ConfigurationTest
  - TEST=fr.inria.astor.test.repair.core.ValidationTest
  - TEST=fr.inria.astor.test.repair.core.StatsTest
  - TEST=fr.inria.astor.test.repair.core.VariableResolverTest
  - TEST=fr.inria.astor.test.repair.core.PatchDiffTest
  - TEST=fr.inria.astor.test.repair.core.PlugInLoaderTest
  - TEST=fr.inria.astor.test.repair.core.PatchValidationTest
  - TEST=fr.inria.astor.test.repair.core.OutputTest
  - TEST=fr.inria.astor.test.repair.core.ValidationTest
  - TEST=fr.inria.astor.test.repair.evaluation.regression.RepairnatorTest
  - TEST=fr.inria.astor.test.repair.evaluation.regression.LangTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.IngredientScopeTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.IngredientProcessorTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.IngredientPoolTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.operatorselection.SelectionOperatorTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.operatorselection.RepairOperatorTest
  - TEST=fr.inria.astor.test.repair.evaluation.extensionpoints.suspiciousnavigation.SuspiciousNavigationStrategyTest
  - TEST=fr.inria.astor.util.CommandSummaryTest

  global:
    secure: KAXmlzbC3aTis3In/HnYpLHgnWmcct9ou7cHTGZZhv+8Tu7eta7HPHBQBju+qD4WkAA8PqyjEhOBHHd7GoSVtUY0nHqPRhjKjeQAPHDgA+kvWVVPyzSEar/gCbFqyzf6MhTs5Feq0PkljmfqF/0Omlps06B7qDVmYaALSFIvgrg=
	###added
	secure: Iy9BF1undwwc3rNo9VikWuqdDqyBbGetG/IGVPBW2ciJEuZNwK76jB/DWfhP2pFxWaU3VDFlPUExAHc90R46MOj9PzhALwadKcWN+z4LWio4Pd4x4miejI7NK2rQfWMQacxIfw05zIt9nWvqNGjrEDg5J3hx3G0sa/eyhi5odZLt5AKNxqJTQNiVv1STZJSntssKhaweVqdnwg3/B1kXEvSyA6Em1/4DhcUEYSBpgvKTfV0+BeoISorEqsR+T3Nrqx48t0fDFzZwd/oMRAjD//loNHebwdxNhAmr+NXlMUXlqdGLgUYTPI+kF9ESgrY7mKkuN4WSc0d8Di3HuznvRvmStMX11OFnblY2OOjPPFEmk4eQW1N/t8oqqHNPpHDpTeHAPL3CLitP66R6d1H0y5megj6WiQeN9Y0lmtB6knUdG4Vmdj3M7aKHVgKGMvgRBfTqF9jQrRbGYxdmnBeq66VKKuxKINr2DQEsL4PzXdb/xBUz1DmAieUprc74ttp5K7uHFNrGOEhSYoHB0iCmSUUl3hAHJgdVKPNJK7LP2dqZwm5mVGEd+LTDCHHOzhxArD2c5CkzWRVFAbDS3r1ExueaC8jrLSrik0l/C82ih+uG247UMXq9RV+ch3ZB4/VYTN2cCTQ0HQIoHYaghW5UAFfwxcIpbnp0qs6y+XF76Qc=
	
dist: trusty
script:
- mvn -ff -q clean
- mvn -ff -q test -DskipTests -DfailIfNoTests=false
- mvn -ff -q surefire:test -DfailIfNoTests=false -Dtest=$TEST
sudo: true #required
before_script:
 - "echo Java_OPTS $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx4096m"
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
 # - examples/
after_success:
#- bash <(curl -s https://codecov.io/bash)
#- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TEST == "fr.inria.astor.test.repair.approaches.JGenProgTest"
#  ]] && { mvn -ff -q versions:set -DnewVersion=`git rev-parse HEAD`; mvn -ff -q deploy --settings .travis-settings.xml -DskipTests=true -B; };'
- "./.travis-deploy.sh"

